const DEFAULT_API_ROOT='https://content-os-flax.vercel.app';
const API_ROOT=(localStorage.getItem('contentos_api_root')||window.CONTENTOS_API_BASE||DEFAULT_API_ROOT).replace(/\/$/,'');
const API_BASE=window.CONTENTOS_DASHBOARD_API_BASE||`${API_ROOT}/api/dashboard`;
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const token=()=>localStorage.getItem('contentos_api_token')||'';
async function request(path,options={}){const h={Accept:'application/json',...(options.headers||{})};if(token())h.Authorization=`Bearer ${token()}`;if(options.body!==undefined)h['Content-Type']='application/json';const r=await fetch(API_BASE+path,{...options,headers:h});if(!r.ok){let d=`HTTP ${r.status}`;try{const j=await r.json();d=j.detail||d}catch{}throw Error(d)}return r.status===204?null:r.json()}
async function rootRequest(path,options={}){const h={Accept:'application/json',...(options.headers||{})};if(token())h.Authorization=`Bearer ${token()}`;if(options.body!==undefined)h['Content-Type']='application/json';const r=await fetch(API_ROOT+path,{...options,headers:h});if(!r.ok){let d=`HTTP ${r.status}`;try{const j=await r.json();d=j.detail||d}catch{}throw Error(d)}return r.json()}
function button(label,fn,cls='secondary'){return `<button class="btn ${cls}" onclick="${fn}">${esc(label)}</button>`}
function show(name){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));document.querySelectorAll('#nav button').forEach(x=>x.classList.toggle('active',x.dataset.page===name));const f={overview:showOverview,research:showResearch,ideas:showIdeas,review:showReview,scripts:showScripts,production:showProduction,publishing:showPublishing,analytics:showAnalytics,learning:showLearning,automation:showAutomation,ai:showAI,settings:showSettings};return (f[name]||showSettings)()}
async function showOverview(){document.getElementById('overview').classList.add('active');try{const[o,ideas]=await Promise.all([request('/overview'),request('/ideas?limit=8')]);[['o-research','research_items'],['o-ideas','ideas'],['o-approved','approved'],['o-published','published'],['p-research','research_items'],['p-ideas','ideas'],['p-review','review'],['p-scripts','scripts'],['p-production','production'],['p-published','published']].forEach(([id,k])=>$(id).textContent=o[k]??0);$('overview-table').innerHTML=ideas.length?ideas.map(i=>`<tr><td>${esc(i.title)}</td><td>${esc(i.topic)}</td><td class="score">${i.overall_score??'—'}</td><td><span class="badge">${esc(i.status)}</span></td></tr>`).join(''):`<tr><td colspan="4" class="muted">No ideas yet. Run Research to populate the pipeline.</td></tr>`;$('system').textContent='● System healthy';$('system').className='status good'}catch(e){$('system').textContent='● API offline';$('system').className='status bad';console.error(e)}}
function showResearch(){document.getElementById('research').classList.add('active')}
async function resolveChannels(){const raw=$('channels').value.split(/[\n,]+/).map(x=>x.trim()).filter(Boolean);if(!raw.length)return;$('resolved').innerHTML='<div class="muted">Resolving…</div>';try{const r=await rootRequest('/api/research/youtube/resolve',{method:'POST',body:JSON.stringify({channel_ids:raw})});$('resolved').innerHTML=[...r.resolved.map(x=>`<span class="chip good">${esc(x.input)}<small>${esc(x.channel_id)}</small></span>`),...r.failed.map(x=>`<span class="chip bad">${esc(x.input)}<small>${esc(x.error)}</small></span>`)].join('')}catch(e){$('resolved').innerHTML=`<div class="error">${esc(e.message)}</div>`}}
async function runResearch(){const b=$('research-run');b.disabled=true;b.textContent='Researching…';try{const channels=$('channels').value.split(/[\n,]+/).map(x=>x.trim()).filter(Boolean);if(!channels.length)throw Error('Enter at least one YouTube channel.');const r=await rootRequest('/api/research/youtube',{method:'POST',body:JSON.stringify({channel_ids:channels,query:$('query').value.trim(),limit:Number($('limit').value||20),generate_ideas:true})});$('research-msg').innerHTML=`<span class="success">Found ${r.research_items_found} research items and created ${r.ideas_created} ideas.</span>`;$('research-results').innerHTML=r.research.map(x=>`<div class="item"><strong>${esc(x.title)}</strong><div class="muted">${esc(x.source_name||'YouTube')} · ${esc(x.published_at||'')}</div><p>${esc(x.summary)}</p>${x.url?`<a class="link" href="${esc(x.url)}" target="_blank" rel="noopener noreferrer">Open source</a>`:''}</div>`).join('')||'<div class="empty">No results.</div>';$('research-ideas').innerHTML=r.ideas.map(ideaCard).join('')||'<div class="empty">No ideas generated.</div>'}catch(e){$('research-msg').innerHTML=`<span class="error">${esc(e.message)}</span>`}finally{b.disabled=false;b.textContent='Run Research'}}
function ideaCard(i,actions=true){const scores=[['Demand',i.demand],['Curiosity',i.curiosity],['Opportunity',i.competition],['Monetization',i.monetization],['Production',i.production]];return `<article class="idea-card"><div class="idea-head"><div><div class="idea-title">${esc(i.title)}</div><div class="muted">${esc(i.topic)} · ${esc(i.audience)}</div></div><div><span class="score big">${i.overall_score??'—'}/10</span> <span class="badge">${esc(i.status)}</span></div></div><p><strong>Hook:</strong> ${esc(i.hook)}</p><p class="muted"><strong>Why now:</strong> ${esc(i.why_now||'Evidence review required')}</p><p class="muted"><strong>Monetization:</strong> ${esc(i.monetization_angle||'—')}</p><div class="score-grid">${scores.map(x=>`<div class="score-box"><span class="muted">${x[0]}</span><strong>${x[1]}/10</strong></div>`).join('')}</div>${i.source?`<div class="muted">Source: ${esc(i.source)}</div>`:''}${actions?`<div class="idea-actions">${i.status==='DISCOVERED'?button('Send to Review',`setIdea('${i.idea_id}','SHORTLISTED')`,'primary'):''}${i.status==='SHORTLISTED'?button('Open Review',`setIdea('${i.idea_id}','REVIEW')`,'primary'):''}${i.status==='REVIEW'?button('Approve',`setIdea('${i.idea_id}','APPROVED')`,'primary'):''}${!['REJECTED','PUBLISHED','ANALYZING'].includes(i.status)?button('Reject',`setIdea('${i.idea_id}','REJECTED')`,'danger'):''}${i.status==='APPROVED'?button('Create Script',`createScript('${i.idea_id}')`,'secondary'):''}</div>`:''}</article>`}
async function loadIdeas(){try{const status=$('idea-filter').value;const data=await request('/ideas?limit=100'+(status?'&status='+encodeURIComponent(status):''));$('ideas-list').innerHTML=data.length?data.map(ideaCard).join(''):'<div class="empty">No ideas match this filter.</div>';$('idea-count').textContent=`${data.length} ideas`}catch(e){$('ideas-list').innerHTML=`<div class="error">${esc(e.message)}</div>`}}
function showIdeas(){document.getElementById('ideas').classList.add('active');loadIdeas()}
async function setIdea(id,status){try{await request(`/ideas/${id}/status`,{method:'PATCH',body:JSON.stringify({status})});show(status==='APPROVED'?'review':'ideas')}catch(e){alert(e.message)}}
async function loadReview(){await showReview()}
async function showReview(){document.getElementById('review').classList.add('active');try{const data=await request('/ideas?limit=100');const groups={SHORTLISTED:[],REVIEW:[],APPROVED:[],REJECTED:[]};data.forEach(x=>groups[x.status]?.push(x));$('review-board').innerHTML=Object.entries(groups).map(([k,v])=>`<div class="review-column"><div class="column-head"><h3>${k}</h3><span>${v.length}</span></div>${v.length?v.map(i=>`<div class="mini-idea"><div class="small-title">${esc(i.title)}</div><div class="score">${i.overall_score}/10</div><div class="muted">${esc(i.hook)}</div><div class="mini-actions">${k==='SHORTLISTED'?button('Review',`setIdea('${i.idea_id}','REVIEW')`,'secondary'):''}${k==='REVIEW'?button('Approve',`setIdea('${i.idea_id}','APPROVED')`,'primary'):''}${!['REJECTED','APPROVED'].includes(k)?button('Reject',`setIdea('${i.idea_id}','REJECTED')`,'danger'):''}${k==='APPROVED'?button('Script',`createScript('${i.idea_id}')`,'secondary'):''}</div></div>`).join(''):'<div class="muted">Empty</div>'}</div>`).join('')}catch(e){$('review-board').innerHTML=`<div class="error">${esc(e.message)}</div>`}}
async function createScript(id){try{await request('/scripts/draft',{method:'POST',body:JSON.stringify({idea_id:id})});show('scripts')}catch(e){alert(e.message)}}
async function showScripts(){document.getElementById('scripts').classList.add('active');try{const[data,ideas]=await Promise.all([request('/scripts'),request('/ideas?limit=100&status=APPROVED')]);$('script-ideas').innerHTML=ideas.length?ideas.map(i=>`<div class="mini-idea"><strong>${esc(i.title)}</strong><div class="mini-actions">${button('Create Draft',`createScript('${i.idea_id}')`,'primary')}</div></div>`).join(''):'<div class="muted">Approve an idea to create a script.</div>';$('scripts-list').innerHTML=data.length?data.map(s=>`<article class="script-card"><div class="idea-head"><div><h3>${esc(s.title)}</h3><div class="muted">Version ${s.version} · ${esc(s.script_id)}</div></div>${button('Create Production Job',`createProduction('${s.script_id}')`,'primary')}</div><p><strong>Hook:</strong> ${esc(s.hook)}</p>${s.sections.map(sec=>`<details><summary>${esc(sec.heading)}</summary><p>${esc(sec.narration)}</p><div class="muted">Visuals: ${esc(sec.visual_notes)}</div></details>`).join('')}<p><strong>Closing:</strong> ${esc(s.closing)}</p><div class="notice">Fact-check: ${s.fact_check_required.map(esc).join(' ')}</div></article>`).join(''):'<div class="empty">No scripts yet.</div>'}catch(e){$('scripts-list').innerHTML=`<div class="error">${esc(e.message)}</div>`}}
async function createProduction(scriptId){try{await request('/production',{method:'POST',body:JSON.stringify({script_id:scriptId})});show('production')}catch(e){alert(e.message)}}
async function showProduction(){document.getElementById('production').classList.add('active');try{const d=await request('/production');$('production-list').innerHTML=d.length?d.map(x=>`<div class="row-card"><div><strong>${esc(x.production_id)}</strong><div class="muted">Script: ${esc(x.script_id)}</div></div><span class="badge">${esc(x.status)}</span><div class="mini-actions">${['QUEUED','ASSETS','RENDERING','READY','FAILED'].map(s=>button(s,`setProduction('${x.production_id}','${s}')`,s==='FAILED'?'danger':'secondary')).join('')}</div></div>`).join(''):'<div class="empty">No production jobs.</div>'}catch(e){$('production-list').innerHTML=`<div class="error">${esc(e.message)}</div>`}}
async function setProduction(id,status){try{await request(`/production/${id}/status`,{method:'PATCH',body:JSON.stringify({status})});show('production')}catch(e){alert(e.message)}}
async function showPublishing(){document.getElementById('publishing').classList.add('active');try{const d=await request('/publishing');$('publish-form').innerHTML=pageForm('New Publish Record',`<div class="form-grid"><input id="pub-production" placeholder="Production ID"><input id="pub-title" placeholder="Video title"><input id="pub-tags" placeholder="Tags, comma separated"></div><textarea id="pub-description" placeholder="Description"></textarea>${button('Create Draft','createPublish()','primary')}`);$('publishing-list').innerHTML=d.length?d.map(x=>`<div class="row-card"><div><strong>${esc(x.title)}</strong><div class="muted">${esc(x.production_id)} · ${esc(x.publish_id)}</div></div><span class="badge">${esc(x.status)}</span><div class="mini-actions">${['DRAFT','SCHEDULED','PUBLISHED','FAILED'].map(s=>button(s,`setPublish('${x.publish_id}','${s}')`,s==='FAILED'?'danger':'secondary')).join('')+(x.status==='DRAFT'?button('Upload to YouTube',`uploadToYouTube('${x.publish_id}')`,'primary'):'')}</div></div>`).join(''):'<div class="empty">No publishing records.</div>'}catch(e){$('publishing-list').innerHTML=`<div class="error">${esc(e.message)}</div>`}}
function pageForm(title,body){return `<div class="card"><h2>${title}</h2>${body}</div>`}
async function createPublish(){try{await request('/publishing',{method:'POST',body:JSON.stringify({production_id:$('pub-production').value.trim(),title:$('pub-title').value.trim(),tags:$('pub-tags').value.split(',').map(x=>x.trim()).filter(Boolean),description:$('pub-description').value})});show('publishing')}catch(e){alert(e.message)}}
async function uploadToYouTube(id){try{const privacy=prompt('YouTube privacy: private, unlisted, or public','private')||'private';if(!['private','unlisted','public'].includes(privacy))throw Error('Privacy must be private, unlisted, or public.');const r=await request('/publishing/'+encodeURIComponent(id)+'/youtube',{method:'POST',body:JSON.stringify({privacy_status:privacy})});alert('Published to YouTube. Video ID: '+r.external_id);show('publishing')}catch(e){alert(e.message)}}
async function setPublish(id,status){try{await request(`/publishing/${id}/status`,{method:'PATCH',body:JSON.stringify({status})});show('publishing')}catch(e){alert(e.message)}}
async function showAnalytics(){document.getElementById('analytics').classList.add('active');try{const d=await request('/analytics');$('analytics-form').innerHTML=pageForm('Record YouTube Metrics',`<div class="form-grid"><input id="m-video" placeholder="Video ID"><input id="m-views" type="number" min="0" placeholder="Views"><input id="m-impressions" type="number" min="0" placeholder="Impressions"><input id="m-ctr" type="number" min="0" max="100" step=".01" placeholder="CTR %"><input id="m-avd" type="number" min="0" step=".1" placeholder="Avg view duration (sec)"><input id="m-watch" type="number" min="0" step=".1" placeholder="Watch time (min)"><input id="m-likes" type="number" min="0" placeholder="Likes"><input id="m-comments" type="number" min="0" placeholder="Comments"><input id="m-subs" type="number" min="0" placeholder="Subscribers gained"><input id="m-revenue" type="number" min="0" step=".01" placeholder="Revenue">${button('Record Metrics','recordMetrics()','primary')}</div>`);$('analytics-list').innerHTML=d.length?d.map(x=>`<div class="row-card"><div><strong>${esc(x.external_video_id)}</strong><div class="muted">${esc(x.captured_at)}</div></div><div>Views <b>${x.views}</b> · CTR <b>${x.click_through_rate}%</b> · AVD <b>${x.average_view_duration_seconds}s</b></div>${button('Analyze',`analyzeMetric('${x.metric_id}')`,'secondary')}</div>`).join(''):'<div class="empty">No metrics recorded.</div>'}catch(e){$('analytics-list').innerHTML=`<div class="error">${esc(e.message)}</div>`}}
async function recordMetrics(){try{const n=id=>Number($(id).value||0);await request('/analytics',{method:'POST',body:JSON.stringify({external_video_id:$('m-video').value.trim(),views:n('m-views'),impressions:n('m-impressions'),click_through_rate:n('m-ctr'),average_view_duration_seconds:n('m-avd'),watch_time_minutes:n('m-watch'),likes:n('m-likes'),comments:n('m-comments'),subscribers_gained:n('m-subs'),revenue:n('m-revenue')})});show('analytics')}catch(e){alert(e.message)}}
async function analyzeMetric(id){try{const r=await request('/analytics/analyze/'+encodeURIComponent(id),{method:'POST'});alert(`Generated ${r.signals.length} learning signals.`);show('learning')}catch(e){alert(e.message)}}
async function showLearning(){document.getElementById('learning').classList.add('active');try{const d=await request('/learning');$('learning-form').innerHTML=pageForm('Add Learning Signal',`<div class="form-grid"><input id="l-video" placeholder="Optional video ID"><input id="l-type" placeholder="Signal type, e.g. HOOK"><input id="l-confidence" type="number" min="0" max="1" step=".1" value=".5"></div><textarea id="l-observation" placeholder="What did we learn?"></textarea>${button('Record Signal','recordLearning()','primary')}`);$('learning-list').innerHTML=d.length?d.map(x=>`<div class="row-card"><div><strong>${esc(x.signal_type)}</strong><div class="muted">${esc(x.source_video_id||'No video')} · ${esc(x.created_at)}</div></div><div>${esc(x.observation)}</div><span class="badge">${x.confidence}</span></div>`).join(''):'<div class="empty">No learning signals yet.</div>'}catch(e){$('learning-list').innerHTML=`<div class="error">${esc(e.message)}</div>`}}
async function recordLearning(){try{await request('/learning',{method:'POST',body:JSON.stringify({source_video_id:$('l-video').value.trim()||null,signal_type:$('l-type').value.trim(),observation:$('l-observation').value.trim(),confidence:Number($('l-confidence').value)})});show('learning')}catch(e){alert(e.message)}}
async function showAutomation(){document.getElementById('automation').classList.add('active');try{const d=await request('/automation');$('automation-form').innerHTML=pageForm('Queue Automation Job',`<div class="form-grid"><input id="a-type" placeholder="Job type"><textarea id="a-payload" placeholder='JSON payload'></textarea>${button('Queue Job','addAutomation()','primary')}</div>`);$('automation-list').innerHTML=d.length?d.map(x=>`<div class="row-card"><div><strong>${esc(x.job_type)}</strong><div class="muted">${esc(x.job_id)}</div></div><span class="badge">${esc(x.status)}</span><div class="mini-actions">${['QUEUED','RUNNING','SUCCEEDED','FAILED'].map(s=>button(s,`setAutomation('${x.job_id}','${s}')`,s==='FAILED'?'danger':'secondary')).join('')}</div></div>`).join(''):'<div class="empty">No automation jobs.</div>'}catch(e){$('automation-list').innerHTML=`<div class="error">${esc(e.message)}</div>`}}
async function addAutomation(){try{let payload={};const raw=$('a-payload').value.trim();if(raw)payload=JSON.parse(raw);await request('/automation',{method:'POST',body:JSON.stringify({job_type:$('a-type').value.trim(),payload})});show('automation')}catch(e){alert(e.message)}}
async function setAutomation(id,status){try{await request(`/automation/${id}/status`,{method:'PATCH',body:JSON.stringify({status})});show('automation')}catch(e){alert(e.message)}}
async function showAI(){document.getElementById('ai').classList.add('active');try{const[s,h]=await Promise.all([request('/settings'),rootRequest('/health')]);$('ai-content').innerHTML=`<div class="card"><div class="connection"><span class="dot good"></span><strong>API connected</strong></div><table class="table"><tr><td>Environment</td><td>${esc(s.environment)}</td></tr><tr><td>Database</td><td>${esc(h.database)}</td></tr><tr><td>LLM provider</td><td>${esc(s.llm_provider||'Not configured')}</td></tr><tr><td>LLM model</td><td>${esc(s.llm_model||'Not configured')}</td></tr></table><div class="notice">AI provider boundaries exist, but external LLM generation is not enabled until a provider implementation and credentials are configured.</div></div>`}catch(e){$('ai-content').innerHTML=`<div class="error">${esc(e.message)}</div>`}}
async function showSettings(){document.getElementById('settings').classList.add('active');try{const s=await request('/settings');$('settings-content').innerHTML=`<div class="card"><h2>Connection</h2><div class="form-grid"><div><label>Dashboard API base</label><input id="setting-api" value="${esc(API_ROOT)}"></div><div><label>API token</label><input id="setting-token" type="password" placeholder="Optional"></div><div>${button('Save','saveSettings()','primary')}</div></div><p class="muted">The API base is persisted in this browser. The token is stored only in local storage.</p></div><div class="card section"><h2>Runtime</h2><table class="table"><tr><td>Environment</td><td>${esc(s.environment)}</td></tr><tr><td>Database</td><td>${esc(s.database)}</td></tr><tr><td>LLM provider</td><td>${esc(s.llm_provider||'Not configured')}</td></tr><tr><td>LLM model</td><td>${esc(s.llm_model||'Not configured')}</td></tr><tr><td>Server API token</td><td>${s.api_token_configured?'Configured':'Not configured'}</td></tr></table></div>`}catch(e){$('settings-content').innerHTML=`<div class="error">${esc(e.message)}</div>`}}
function saveSettings(){const base=$('setting-api').value.trim().replace(/\/$/,'');if(!base)return alert('API base is required.');localStorage.setItem('contentos_api_root',base);const t=$('setting-token').value;if(t)localStorage.setItem('contentos_api_token',t);else localStorage.removeItem('contentos_api_token');alert('Saved. Reload the dashboard to use the new API base.')}
document.addEventListener('DOMContentLoaded',()=>{document.querySelectorAll('#nav button').forEach(b=>b.addEventListener('click',()=>show(b.dataset.page)));show('overview');setInterval(()=>{if(document.querySelector('#overview.page.active'))showOverview()},30000)});
